let displayItemsData = [
    {
        id: "1354545148",
        incontrounable: true,
        titre: "Cadrage projet",
        categorie: "STRATEGIE",
        criteres: "Le besoin métier est-il exprimé ?",
        cycledevie: "Conception",
        indicateur: "(X / Y ) * 100",
        Xindicateur: "Expression rédigée et validée = 100 ; Expression formalisée = 75 ; Tacite = 30 ; Non = 0",
        Yindicateur: "100",
    }
    ,
    {
        id: "584695648956",
        incontrounable: true,
        titre: "Emergence",
        categorie: "STRATEGIE",
        criteres: "Le besoin couvert par le service numérique s'inscrit-il dans l'un des objectifs de développement durable?",
        cycledevie: "Conception",
        indicateur: "(X / Y ) * 100",
        Xindicateur: "Au moins 1 ODD couvert = 100 ; 0 ODD = 0",
        Yindicateur: "100",
    }
    ,
    {
        id: "54485648564",
        incontrounable: true,
        titre: "Emergence",
        categorie: "STRATEGIE",
        criteres: "Les parties prenantes internes et externes sont-elles sensibilisées, voire formées/certifiées au NR ?",
        cycledevie: "",
        indicateur: "(X / Y ) * 100",
        Xindicateur: "Sensibilisations NR",
        Yindicateur: "Membre équipe",
    }
    ,
    {
        id: "5955845626588959",
        incontrounable: true,
        titre: "Emergence",
        categorie: "STRATEGIE",
        criteres: "La conformité numérique responsable est-elle exposée ?",
        cycledevie: "Conception",
        indicateur: "(X / Y ) * 100",
        Xindicateur: "Document validé et exposé = 100 ; Partiel = 50 ; Prévu = 25 ; Non = 0",
        Yindicateur: "100",
    }
    ,
    {
        id: "56953565656996556",
        incontrounable: true,
        titre: "Equipe projet",
        categorie: "STRATEGIE",
        criteres: "Les enjeux NR du projet ont-ils été communiqués é l'équipe dés l'origine ?",
        cycledevie: "",
        indicateur: "(X / Y ) * 100",
        Xindicateur: "Enjeux NR communiqués",
        Yindicateur: "Enjeux NR communiqués",
    }
    ,
    {
        id: "35632135324563",
        incontrounable: true,
        titre: "Equipe projet",
        categorie: "STRATEGIE",
        criteres: "Chaque entité de l'équipe Projet dispose-t-elle des compétences NR ?",
        cycledevie: "",
        indicateur: "(X / Y ) * 100",
        Xindicateur: "Plan de formation NR = 100 ; Mise é dispo de ressources NR = 50 ; Non = 0",
        Yindicateur: "100",
    }
    ,
    {
        id: "21565621463215546",
        incontrounable: true,
        titre: "Methodologie projet",
        categorie: "STRATEGIE",
        criteres: "Quelle proportion des fonctionnalités (User Story) ont une composante NR ? ",
        cycledevie: "Conception",
        indicateur: "(X / Y ) * 100",
        Xindicateur: "Nombre US avec info NR",
        Yindicateur: "Nombre US",
    }
    ,
    {
        id: "6514154869625685",
        incontrounable: true,
        titre: "Processus economique",
        categorie: "STRATEGIE",
        criteres: "Dans le processus d'achat (Appel d'offre) des exigences d'engagement NR sont-elles demandées aux prestataires externes ?",
        cycledevie: "Acquisition",
        indicateur: "(X / Y ) * 100",
        Xindicateur: "Exigences NR dans AO",
        Yindicateur: "Appel d'offres",
    }
    ,
    {
        id: "4784547864789",
        incontrounable: true,
        titre: "Gestion du cycle de vie",
        categorie: "STRATEGIE",
        criteres: "Les données et procédures spécifiées ont-elles toutes une information de fin de vie ?",
        cycledevie: "Fin de vie",
        indicateur: "(X / Y ) * 100",
        Xindicateur: "Formalisés = 100 ; prévus = 75 ; Identifiés = 50 ; Non = 0",
        Yindicateur: "100",
    }
    ,
    {
        id: "454856446494",
        incontrounable: true,
        titre: "Méthodologie",
        categorie: "Ux/Ui",
        criteres: "Dans les méthodes d'idéation, l'ensemble des parties prenantes est-il pris en compte dans toute sa dimension (humaine) ?",
        cycledevie: "Conception",
        indicateur: "(X / Y ) * 100",
        Xindicateur: "Formalisés = 100 ; prévus = 75 ; Identifiés = 50 ; Non = 0",
        Yindicateur: "100",
    }
    ,
    {
        id: "7894561258",
        incontrounable: true,
        titre: "Methodologie",
        categorie: "Ux/Ui",
        criteres: "La planéte est-elle prise en compte dans les méthodes d'idéation pour intégrer la dimension écologique (planet centric design) ?",
        cycledevie: "Conception",
        indicateur: "(X / Y ) * 100",
        Xindicateur: "Formalisés = 100 ; prévus = 75 ; Identifiés = 50 ; Non = 0",
        Yindicateur: "100",
    }
    ,
    {
        id: "4562368756",
        incontrounable: true,
        titre: "Methodologie",
        categorie: "Ux/Ui",
        criteres: "Les plus-values extra-financiéres du numérique responsable sont-elles valorisées dans le business model ?",
        cycledevie: "Utilisation",
        indicateur: "(X / Y ) * 100",
        Xindicateur: "Formalisés = 100 ; prévus = 75 ; Identifiés = 50 ; Non = 0",
        Yindicateur: "100",
    }
    ,
    {
        id: "54944941616",
        incontrounable: true,
        titre: "Ressources projet",
        categorie: "Ux/Ui",
        criteres: "Les parties prenantes sont-elles sensibilisées au NR ?",
        cycledevie: "",
        indicateur: "(X / Y ) * 100",
        Xindicateur: "Sensibilisations NR",
        Yindicateur: "Membre équipe",
    }
    ,
    {
        id: "46984652398",
        incontrounable: true,
        titre: "Methodologie",
        categorie: "Ux/Ui",
        criteres: "Une stratégie de compatibilité avec les terminaux et versions logicielles obsolétes est-elle définie ?",
        cycledevie: "Utilisation",
        indicateur: "(X / Y ) * 100",
        Xindicateur: "Formalisés = 100 ; prévus = 75 ; Identifiés = 50 ; Non = 0",
        Yindicateur: "100",
    }
    ,
    {
        id: "4415613268",
        incontrounable: true,
        titre: "Methodologie",
        categorie: "Ux/Ui",
        criteres: "Dés la conception, le service répond-t-il aux normes d'accessibilité en vigueur (au minimum) ?",
        cycledevie: "Conception",
        indicateur: "(X / Y ) * 100",
        Xindicateur: "Formalisés = 100 ; prévus = 75 ; Identifiés = 50 ; Non = 0",
        Yindicateur: "100",
    }
    ,
    {
        id: "145256269694",
        incontrounable: true,
        titre: "UI",
        categorie: "Ux/Ui",
        criteres: "Une sobriété visuelle est-elle mise en place, pour limiter les ressources énergétiques et l'impact sur la dégradation matérielle des composants visuels, sonores et tactiles constitutifs de l'interface ?",
        cycledevie: "Réalisation",
        indicateur: "(X / Y ) * 100",
        Xindicateur: "Formalisés = 100 ; prévus = 75 ; Identifiés = 50 ; Non = 0",
        Yindicateur: "100",
    }
    ,
    {
        id: "4515156551",
        incontrounable: true,
        titre: "Methodologie",
        categorie: "Ux/Ui",
        criteres: "Est-ce que les fonctionnalités sont utilisées par l'utilisateur ?",
        cycledevie: "Utilisation",
        indicateur: "(X / Y ) * 100",
        Xindicateur: "Validations d'utilisation",
        Yindicateur: "Fonctionnalités",
    }
    ,
    {
        id: "45151565578",
        incontrounable: true,
        titre: "UI",
        categorie: "Ux/Ui",
        criteres: "Une politique de gestion/utilisation des médias afin de réduire leurs impacts est-elle en place, avec des critéres de compression et de formats des médias ?",
        cycledevie: "Realisation",
        indicateur: "(X / Y ) * 100",
        Xindicateur: "Medias compréssés",
        Yindicateur: "Support media",
    }
    ,
    {
        id: "4515156456",
        incontrounable: true,
        titre: "UI",
        categorie: "Ux/Ui",
        criteres: "Le nombre de polices de caractéres (fonts) et les variantes de polices appelées (graisse, caractéres utilisés dans le projet) sont-ils limités ?",
        cycledevie: "Conception",
        indicateur: "(X / Y ) * 100",
        Xindicateur: "Moins de 3 polices = 100 ; 3-5 polices = 50 ; Plus de 5 = 0",
        Yindicateur: "100",
    }
    ,

    {
        id: "4515165652",
        incontrounable: true,
        titre: "Méthodologie",
        categorie: "Ux/Ui",
        criteres: "Le service évite-t-il les Dark Patterns ?",
        cycledevie: "Conception",
        indicateur: "(X / Y ) * 100",
        Xindicateur: "Formalisés = 100 ; prévus = 75 ; Identifiés = 50 ; Non = 0",
        Yindicateur: "100",
    }
    ,
    {
        id: "4541585666",
        incontrounable: true,
        titre: "Usage",
        categorie: "Ux/Ui",
        criteres: "Des régles en matiére de respect de l'utilisateur sont-elles mises en place ?  ",
        cycledevie: "Conception",
        indicateur: "(X / Y ) * 100",
        Xindicateur: "Formalisés = 100 ; prévus = 75 ; Identifiés = 50 ; Non = 0",
        Yindicateur: "100",
    }
    ,
    {
        id: "78945777",
        incontrounable: true,
        titre: "",
        categorie: "CONTENUS",
        criteres: "Les balises de mise en forme de texte répondent-elles au besoin de hiérarchisation des informations, et pas é des mises en valeur de présentation ?",
        cycledevie: "Réalisation",
        indicateur: "(X / Y ) * 100",
        Xindicateur: "Tags analysés",
        Yindicateur: "Tags Hx",
    }
    ,
    {
        id: "123456999",
        incontrounable: true,
        titre: "Images",
        categorie: "CONTENUS",
        criteres: "Est-ce  que les images ont été compressées en amont dans un format adapté pour sa visualisation ?",
        cycledevie: "Réalisation",
        indicateur: "(X / Y ) * 100",
        Xindicateur: "Images compressés",
        Yindicateur: "Images",
    }
    ,
    {
        id: "456781111",
        incontrounable: true,
        titre: "Videos",
        categorie: "CONTENUS",
        criteres: "Est-ce que l'information portée par la vidéo peut étre remplacée par une alternative (infographie...)",
        cycledevie: "Conception",
        indicateur: "(X / Y ) * 100",
        Xindicateur: "Videos analysées",
        Yindicateur: "Videos",
    }
    ,
    {
        id: "77788855556",
        incontrounable: true,
        titre: "Telechargements",
        categorie: "CONTENUS",
        criteres: "Les documents é télécharger sont-ils compressés, optimisés et accessibles ?",
        cycledevie: "Deploiement",
        indicateur: "(X / Y ) * 100",
        Xindicateur: "Documents compressés",
        Yindicateur: "Documents disponibles",
    }
    ,
    {
        id: "111559933",
        incontrounable: true,
        titre: "Cycle de vie",
        categorie: "ARCHITECTURE",
        criteres: "Est-ce que les environnements autres que production (DEV, QA, ...) sont éteints ou décommissionnés en dehors des plages d'usage (la nuit, en dehors des périodes de tests)?",
        cycledevie: "Administration",
        indicateur: "(X / Y ) * 100",
        Xindicateur: "Formalisés = 100 ; prévus = 75 ; Identifiés = 50 ; Non = 0",
        Yindicateur: "100",
    }
    ,
    {
        id: "111557744666",
        incontrounable: true,
        titre: "Cycle de vie",
        categorie: "ARCHITECTURE",
        criteres: "Chaque composant déployé est-il qualifié du point de vue de sa durée de vie, et les procédures de déprovisonnement sont-elles systématiquement exprimées ?",
        cycledevie: "Fin de vie",
        indicateur: "(X / Y ) * 100",
        Xindicateur: "Formalisés = 100 ; prévus = 75 ; Identifiés = 50 ; Non = 0",
        Yindicateur: "100",
    }
    ,
    {
        id: "1236585274196",
        incontrounable: true,
        titre: "Design logiciel",
        categorie: "ARCHITECTURE",
        criteres: "L'ensemble des équipements techniques utilisés par le service sont-ils identifiés?",
        cycledevie: "Acquisition",
        indicateur: "(X / Y ) * 100",
        Xindicateur: "Formalisés = 100 ; prévus = 75 ; Identifiés = 50 ; Non = 0",
        Yindicateur: "100",
    }
    ,
    {
        id: "74185963222",
        incontrounable: true,
        titre: "API",
        categorie: "FRONTEND",
        criteres: "Est-ce que les fonctionnalités couvertes par des actions locales (cété client) sont privilégiées plutét que des échanges API ?",
        cycledevie: "Réalisation",
        indicateur: "(X / Y ) * 100",
        Xindicateur: "Fonctionnalités analysées",
        Yindicateur: "Fonctionnalités elligibles",
    }
    ,
    {
        id: "748596233366",
        incontrounable: true,
        titre: "User experience",
        categorie: "FRONTEND",
        criteres: "La plage de rétro-compatibilité est-elle définie ?",
        cycledevie: "Réalisation",
        indicateur: "(X / Y ) * 100",
        Xindicateur: "Formalisés = 100 ; prévus = 75 ; Identifiés = 50 ; Non = 0",
        Yindicateur: "100",
    }
    ,
    {
        id: "456987412366",
        incontrounable: true,
        titre: "Standards de developpement",
        categorie: "FRONTEND",
        criteres: "Les fonctionnalités du service ne vont-elles pas au-delé des besoins utilisateurs ?",
        cycledevie: "Conception",
        indicateur: "(X / Y ) * 100",
        Xindicateur: "Fonctionnalités utilisées",
        Yindicateur: "Fonctionnalités déployées",
    }
    ,
    {
        id: "7788945656145656548541584586585965896589",
        incontrounable: true,
        titre: "UI",
        categorie: "FRONTEND",
        criteres: "Une version épurée est-elle disponible pour les impressions ?",
        cycledevie: "Utilisation",
        indicateur: "(X / Y ) * 100",
        Xindicateur: "Formalisés = 100 ; prévus = 75 ; Identifiés = 50 ; Non = 0",
        Yindicateur: "100",
    }
    ,
    {
        id: "84549655",
        incontrounable: true,
        titre: "UI",
        categorie: "FRONTEND",
        criteres: "Les objets de cartographie, animations, vidéos sont-ils présentés dans un mode statique ?",
        cycledevie: "Réalisation",
        indicateur: "(X / Y ) * 100",
        Xindicateur: "Objets analysés",
        Yindicateur: "Objets dynamiques",
    }
    ,
    {
        id: "1",
        incontrounable: true,
        titre: "Données",
        categorie: "BACKEND",
        criteres: "Est-ce que le nombre de requétes est minimisé (proscrire l'usage de boucle) ?",
        cycledevie: "Réalisation",
        indicateur: "(X / Y ) * 100",
        Xindicateur: "Formalisés = 100 ; prévus = 75 ; Identifiés = 50 ; Non = 0",
        Yindicateur: "100",
    }
    ,
    {
        id: "45685215999",
        incontrounable: true,
        titre: "Qualité",
        categorie: "BACKEND",
        criteres: "Les fonctionnalités sont-elles documentées pour permettre leur réutilisation ?",
        cycledevie: "Revalorisation",
        indicateur: "(X / Y ) * 100",
        Xindicateur: "Formalisés = 100 ; prévus = 75 ; Identifiés = 50 ; Non = 0",
        Yindicateur: "100",
    }
    ,
    {
        id: "54865586548",
        incontrounable: true,
        titre: "Flux",
        categorie: "BACKEND",
        criteres: "Est-ce que les données échangées sont compressées / minifiées avant transmission ?",
        cycledevie: "Deploiement",
        indicateur: "(X / Y ) * 100",
        Xindicateur: "Volume compressé",
        Yindicateur: "Volume de transfert",
    }
    ,
    {
        id: "4564564856",
        incontrounable: true,
        titre: "Cycle de vie",
        categorie: "BACKEND",
        criteres: "Est-ce que la fonctionnalité envisagée est utile ?",
        cycledevie: "Conception",
        indicateur: "(X / Y ) * 100",
        Xindicateur: "Fonctionnalités utilisées",
        Yindicateur: "Fonctionnalités déployées",
    }
    ,

];